###   create service account using following command
#kubectl create sa aneesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aneesh-role
rules:
  - apiGroups: [ "*" ]
    resources: [ "pods/exec","pods","deployments" ]
    verbs: [ "get", "list","edit","create","update","delete"  ]

##### role binding.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aneesh-rb
subjects:
- kind: ServiceAccount
  name: aneesh
  namespace: default
  #  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: aneesh-role
  apiGroup: rbac.authorization.k8s.io


